module.exports = {
  jobFields: [
    "accountancy",
    "administration / management",
    "agriculture / farming",
    "banking / finance / insurance",
    "building / design / architecture",
    "business development",
    "business strategy / planning",
    "charity / voluntary",
    "construction / contract - management",
    "consulting / business strategy and planning",
    "creatives / arts / design / fashion",
    "customer service",
    "digital and creative",
    "education / teaching / training",
    "engineering",
    "estate agency",
    "executive / top management",
    "graduate",
    "healthcare / pharmaceutical",
    "hospitality / leisure / travels",
    "human resources",
    "information technology",
    "IT contractor",
    "law / legal",
    "legal jobs",
    "leisure and tourism jobs",
    "manufacturing / production",
    "marketing / advertising / communications",
    "Marketing and PR",
    "Media",
    "Motoring andcAutomotive",
    "NGO Community Services and Development",
    "oil gas / mining energy",
    "project / programme management",
    "public sector",
    "purchase ledger clerk",
    "purchasing",
    "QA & amp; QC / HSE",
    "real estate / property",
    "retail",
    "sales and marketing",
    "sales / business development",
    "supply chain / procurement",
    "telecommunications",
    "transportation",
    "vocational trade and services",
    "web designing / graphic design",
    "software development",
    "Information Technology"
  ],
  states: [
    "Lagos",
    "Abuja FCT",
    "Rivers",
    "Akwa Ibom",
    "Cross River",
    "Ogun",
    "Bayelsa",
    "Benue",
    "Borno",
    "Anambra",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Abia",
    "Nassarawa",
    "Niger",
    "Bauchi",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Adamawa",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara"
  ],
  jobLevels: [
    "Undergraduate Internship / Vacation Job",
    "Fresh Graduate / Entry Level",
    "Experienced(Non - Manager)",
    "Manager(Staff Supervisor / Head of Department)",
    "Executive(Director / CEO / CFO / COO)"
  ],
  jobExperiences: ["entry level", "1 - 3", "4 - 7", "8 - 12", "13 - 15", "15+"],
  degrees: [
    "MPhil / PhD",
    "MBA / MSc",
    "MBBS",
    "Degree",
    "HND",
    "N.C.E",
    "Diploma(OND)",
    "High School(S.S.C.E)",
    "Vocational",
    "Others"
  ],
  jobAvailabilities: ["full-time", "part-time", "contract", "internship"],
  salaryRanges: [
    "30000 - 100000",
    "101000 - 150000",
    "151000 - 250000",
    "351000+",
    "undisclosed"
  ],
  countries: [
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Indian Ocean Territory",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Colombia",
    "Comoros",
    "Congo",
    "Congo, The Democratic Republic of the",
    "Cook Islands",
    "Costa Rica",
    "Cote D'Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands (Malvinas)",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard Island and Mcdonald Islands",
    "Holy See (Vatican City State)",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran, Islamic Republic Of",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea, Democratic People'S Republic of",
    "Korea, Republic of",
    "Kuwait",
    "Kyrgyzstan",
    "Lao People'S Democratic Republic",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libyan Arab Jamahiriya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "Macedonia, The Former Yugoslav Republic of",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia, Federated States of",
    "Moldova, Republic of",
    "Monaco",
    "Mongolia",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "Netherlands Antilles",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestinian Territory, Occupied",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Reunion",
    "Romania",
    "Russian Federation",
    "RWANDA",
    "Saint Helena",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia and Montenegro",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia and the South Sandwich Islands",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Svalbard and Jan Mayen",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Taiwan, Province of China",
    "Tajikistan",
    "Tanzania, United Republic of",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "United States Minor Outlying Islands",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Viet Nam",
    "Virgin Islands, British",
    "Virgin Islands, U.S.",
    "Wallis and Futuna",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe"
  ]
};
